### ISSUE TITLE
Failure with dev testthat

### ISSUE THREAD

**Issue by hadley** [maxar/IncDTW#4]
With the dev version of testthat I see:

```
── ERROR (test_cm.R:62:4): custom dist function ────────────────────────────────
Error: `desc` must be a string
Backtrace:
    █
 1. └─testthat::test_that(counter, prod(dim(tmp))) test_cm.R:62:3
```

Because `test_that()` now requires a string as the first argument.

I'm planning to submit testthat to CRAN in about a month, so I'd recommend fixing and submitting to CRAN before then.

**Comment by maxar** [comment]
Thanks. That's just a typo, so I guess no concern for testthat 3.0. For any reason I used `test_that()` instead of `expect_equal()`.
